# Generated by Django 3.2.12 on 2024-01-11 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmovement',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
