# Generated by Django 3.2.12 on 2024-01-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdb', '0004_auto_20240111_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
